### PR TITLE
Clews 27620 brazil sugar gpm gfs integration

### PR DESCRIPTION
**Pull request by biquanlin**

### CODE REVIEW

**Comment by biquanlin** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/gro-intelligence/api-client/pull/243/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by biquanlin** [comment]
<p>done. combined it to the first paragraph</p>

---

 <a href='https://app.reviewnb.com/gro-intelligence/api-client/pull/243/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by biquanlin** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/gro-intelligence/api-client/pull/243/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by biquanlin** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/gro-intelligence/api-client/pull/243/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by biquanlin** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/gro-intelligence/api-client/pull/243/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by biquanlin** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/gro-intelligence/api-client/pull/243/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jeanzhaoyi** [comment]
New edits look good to me.

**Review by jeanzhaoyi — APPROVED** [review]

**Review by itsjohnward — APPROVED** [review]

**Pull request merged**
