### PR TITLE
CLEWS-28603: add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by itsjohnward**
Reviewers please let me know if these instructions are clear.

### CODE REVIEW

**Review by seungatGro — APPROVED** [review]
doc LGTM.

however getting this error when installing:

```
sphinx-rtd-theme 0.4.3 requires sphinx, which is not installed.
recommonmark 0.6.0 requires sphinx>=1.3.1, which is not installed.
tsfresh 0.12.0 has requirement pandas<=0.23.4,>=0.20.3, but you'll have pandas 0.24.1 which is incompatible.
```

**Comment by joysaikat** [comment]
@seungatGro Is there a reason we cannot go to pandas 1.0.3?
https://grointelligence.atlassian.net/browse/CLEWS-26600

**Comment by seungatGro** [comment]
> @seungatGro Is there a reason we cannot go to pandas 1.0.3?
> https://grointelligence.atlassian.net/browse/CLEWS-26600

not the savviest with df library... but i dont see why not, other than addressing breaking changes. from issue, im guessing the effort is not prioritized since the original bug is still present in v1.0

**Comment by joysaikat** [comment]
https://github.com/blue-yonder/tsfresh/blob/master/requirements.txt

This is the tsfresh requirements file. Seems like as long as we avoid pandas 0.24.* we should be fine.

**Comment by itsjohnward** [comment]
> doc LGTM.
> 
> however getting this error when installing:
> 
> ```
> sphinx-rtd-theme 0.4.3 requires sphinx, which is not installed.
> recommonmark 0.6.0 requires sphinx>=1.3.1, which is not installed.
> tsfresh 0.12.0 has requirement pandas<=0.23.4,>=0.20.3, but you'll have pandas 0.24.1 which is incompatible.
> ```

Discussed offline - this was due to other dependencies that were already installed and not related to the testing requirements mentioned in this doc.

**Comment by itsjohnward** [comment]
> @seungatGro Is there a reason we cannot go to pandas 1.0.3?
> https://grointelligence.atlassian.net/browse/CLEWS-26600

@joysaikat We're in the Python 2-3 grey area here with pandas and tsfresh:

* Pandas 0.24.2 is the last version that supports Python 2 https://pandas.pydata.org/docs/whatsnew/v0.24.2.html
* Pandas 0.25.0 drops anything below 3.5.3 https://pandas.pydata.org/docs/whatsnew/v0.25.0.html
* Pandas 0.25.2 adds support for Python 3.8 https://pandas.pydata.org/docs/whatsnew/v0.25.2.html
* Pandas 1.0.0 drops anything below Python 3.6.1 https://pandas.pydata.org/docs/whatsnew/v1.0.0.html#increased-minimum-version-for-python

So, at the moment, we support Python `[2.7.12, 3)` and `[3.5, 3.8)`. As we saw in https://github.com/gro-intelligence/api-client/pull/218#issuecomment-632346233 we currently have some problems on 3.8 related to this. And seeing as how Python 2 and Python 3.8 are mutually exclusive in regards to which pandas versions support them, we must deprecate Python 2 sooner rather than later so we can support the latest Python version.

Out of the scope on this PR though. Will bump the relevant Jira issue: https://grointelligence.atlassian.net/browse/CLEWS-23219

**Pull request merged**
