### PR TITLE
V1.40.3 branch

### PR DESCRIPTION
**Pull request by itsjohnward**
The `get_logger()` feature added in https://github.com/gro-intelligence/api-client/pull/111/files#diff-603e79178b8e522d0e366a9fca477b24R44 needs to be included in a released version of the client library so prevent plant can utilize it. Tagging a new version so the update will be received.

### CODE REVIEW

**Review by JGrinst — APPROVED** [review]
Good catch!

**Review by ash-gro — APPROVED** [review]
Looks good to me. In retrospect, get_logger() is a new feature of the main client, so should probably not have added as part of this branch which deals with rewriting one of usage examples (not sure Nemo would agree though).

**Comment by itsjohnward** [comment]
> Looks good to me. In retrospect, get_logger() is a new feature of the main client, so should probably not have added as part of this branch which deals with rewriting one of usage examples (not sure Nemo would agree though).

I agree - I think it's a good approach to have a feature branch merged and tagged prior to merging the updated sample. Make it a pre-req if needing to use a feature from it

**Comment by nemozen** [comment]
> > Looks good to me. In retrospect, get_logger() is a new feature of the main client, so should probably not have added as part of this branch which deals with rewriting one of usage examples (not sure Nemo would agree though).
> 
> I agree - I think it's a good approach to have a feature branch merged and tagged prior to merging the updated sample. Make it a pre-req if needing to use a feature from it

agreed.  this was a backward compatible change and the assumption is that people running new version of sample code would have the most recent client release

**Pull request merged**
