### PR TITLE
more specific search query  for yield metrics

### PR DESCRIPTION
**Pull request by nemozen**
in this example we want to guarantee the top result is the expected metric

### CODE REVIEW

**Review by JGrinst — APPROVED** [review]
LGTM

**Review by itsjohnward — CHANGES_REQUESTED** [review]
This search matching is working as intended now, but I'm getting a divide-by-zero error in crop_model's compute_weights function. This line: `[old_div(mean,total) for mean in means]`

Looking into that now

**Review by itsjohnward — APPROVED** [review]
It was matching on the "Production Quantity" group instead of "production quantity (mass)"

I removed parens from

```
model.compute_crop_weighted_series(
        'soybeans', 'Production Quantity (mass)',
        'Vegetation (NDVI)', 'Vegetation Indices (index)',
        provinces)
```

Changed to:

```
model.compute_crop_weighted_series(
        'soybeans', 'Production Quantity mass',
        'Vegetation NDVI', 'Vegetation Indices index',
        provinces)
```

and that works. Should just working after Simon's special characters search change though, so no change should be necessary here on the client side.

**Comment by nemozen** [comment]
> It was matching on the "Production Quantity" group instead of "production quantity (mass)"
> 
> I removed parens from
> 
> ```
> model.compute_crop_weighted_series(
>         'soybeans', 'Production Quantity (mass)',
>         'Vegetation (NDVI)', 'Vegetation Indices (index)',
>         provinces)
> ```
> Changed to:
> 
> ```
> model.compute_crop_weighted_series(
>         'soybeans', 'Production Quantity mass',
>         'Vegetation NDVI', 'Vegetation Indices index',
>         provinces)
> ```
> and that works. Should just working after Simon's special characters search change though, so no change should be necessary here on the client side.


Thanks! Yes search input escaping should fix it but might as well add the workaround there anyway, it doesn't hurt.  Done.

**Pull request merged**
